### ISSUE TITLE
[Fabric] Curseforge download issue

### ISSUE THREAD

**Issue by DDriggs00** [Reoseah/catwalks-incorporated#10]
Something is preventing this mod from being downloaded as a part of a modpack on third-party launchers. This is typically caused by a misconfigured setting in Curseforge.

**Comment by DDriggs00** [comment]
Also, here's a more detailed appeal written by someone with a bit more experience than me: https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c

**Comment by reoseah** [comment]
Should be fixed now, I think. It doesn't explain what that switch "prevent distribution outside the platform" mean, so I just checked it without giving it much thought

**Comment by DDriggs00** [comment]
Thanks a ton!
