### ISSUE TITLE
Using a wrench on catwalk stairs

### ISSUE THREAD

**Issue by CyborgCabbage** [Reoseah/catwalks-incorporated#2]
Mod Version: 1.0.0
Fabric API Version: 0.44.0
Fabric Loader: 0.12.8

When the wrench is used on the stair version of the catwalk it doesn't work.

**Comment by reoseah** [comment]
Thanks for reporting! Sorry for inconvenience

I indeed broke it in refactoring just before releasing the mod.

**Comment by reoseah** [comment]
Fixed in 1.0.1

Will be available on Curseforge once approved
