### ISSUE TITLE
Server Connection Lost, Registry remapping failed

### ISSUE THREAD

**Issue by nlrose** [Reoseah/catwalks-incorporated#5]
Logged out of All of Fabic 5 public server after using catwalks. Now every time I try to connect to the server I get: 

Connection Lost
Registry remapping failed: Recieved ID map for minecraft:sound_event contains IDs unknown to the reciever!
-catwalksinc:crank_wheel_use
-catwalksinc:wrench_us

**Comment by reoseah** [comment]
I've seen it in AOF discord a moment ago, I suppose I know why it happens (sound events are in a separate class that might never get initialized since it's not referenced...) and that should be fixed that in v1.0.7

Thanks for reporting, I'm sorry for inconvenience

**Comment by nlrose** [comment]
👍
